[package]
name = "cns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "des"
path = "src/bin/des.rs"

[dependencies]
log = "0.4.21"
